# Generated by Django 4.1.3 on 2022-11-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
