# Generated by Django 4.1.3 on 2022-12-06 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideasDB', '0002_outing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('picture_url', models.URLField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('schduled_for', models.DateTimeField(null=True)),
                ('completed_on', models.DateTimeField(null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideasDB.activity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='activity',
            field=models.ManyToManyField(through='ideasDB.UserActivity', to='ideasDB.activity'),
        ),
    ]
