# Generated by Django 4.1.3 on 2022-12-09 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideasDB', '0004_remove_customuser_activity_activity_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='completed_on',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='schduled_for',
        ),
        migrations.AddField(
            model_name='activity',
            name='completed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='scheduled_for',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
