# Generated by Django 4.1.3 on 2022-12-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideasDB', '0005_remove_useractivity_completed_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user_id',
            new_name='user',
        ),
    ]
