# Generated by Django 4.1.3 on 2022-12-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasDB', '0007_remove_activity_completed_on_activity_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='review',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
